bazel_dep(name = "abseil-cpp", version = "20260526.0")
bazel_dep(name = "boringssl", version = "0.20260813.0")
bazel_dep(name = "google_benchmark", version = "1.9.5")
bazel_dep(name = "googletest", version = "1.18.0")
bazel_dep(name = "grpc", version = "1.83.0")
bazel_dep(name = "highway", version = "1.4.0")
bazel_dep(name = "llvm", version = "0.8.17")
bazel_dep(name = "protobuf", version = "35.1")
bazel_dep(name = "re2", version = "2025-11-05.bcr.1")
bazel_dep(name = "riegeli", version = "0.0.0-20250822-9f2744d")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_go", version = "0.62.0")
bazel_dep(name = "rules_java", version = "9.7.1")
bazel_dep(name = "tcmalloc", version = "0.0.0-20250927-12f2552")

http_jar = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")
http_jar(
    name = "copybara",
    sha256 = "5938f1db447c20ff9859828f3d52ce1b04dbe1da18195337f3efae5e65f1d969",
    urls = ["https://github.com/google/copybara/releases/download/v20250224/copybara_deploy.jar"],
)

# Enable hermetic LLVM toolchain
register_toolchains("@llvm//toolchain:all")
