build:
  bazel build -c opt //experimental/1brc --fdo_instrument=./
  ../../bazel-bin/experimental/1brc/1brc > /dev/null
  llvm-profdata merge *.profraw -o fdo.profdata
  rm *.profraw
  bazel build -c opt //experimental/1brc --fdo_optimize=//experimental/1brc:fdo_profile

compile:
  bazel build -c opt //experimental/1brc
